# Generated by Django 6.0.2 on 2026-03-09 15:55

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_chatmember_chat_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='invite_token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=100),
        ),
    ]
