# Generated by Django 6.0.2 on 2026-03-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_chat_invite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='invite_token',
            field=models.CharField(default='vvvTVeOe0Dvl2w', max_length=100),
        ),
    ]
