# Generated by Django 6.0.2 on 2026-04-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_alter_chat_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='ext',
            field=models.CharField(default='.txt', max_length=10),
        ),
        migrations.AlterField(
            model_name='chat',
            name='invite_token',
            field=models.CharField(default='Xv58ziAEDKJWRg', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
